repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.16.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: black
        language-version: python3.11
        args: [--line-length, '88']

      - id: check-yaml

      - id: trailing-whitespace

      - id: end-of-file-fixer

  - repo: https://github.com/pycqa/flake8
    rev: v6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=88]
