version: "3"

services:
  app:
    image: python:3.11
    container_name: eight_queens
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DATABASE_URL: postgresql://mirichi:mirichi@db:5432/eight_queens_db

  db:
    image: postgres:13
    container_name: eight_queens_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network

  flyway:
    image: flyway/flyway:9.9
    environment:
      FLYWAY_URL: postgresql://mirichi:mirichi@db:5432/eight_queens_db
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/migrations:/flyway/sql
    command: ["migrate"]

networks:
  app-network:
    driver: bridge

volumes:
  db:
