version: "3.8"

services:
  db:
    image: postgres:15
    container_name: eight_queens_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    container_name: flyway_migration
    depends_on:
      - db
    command: >
      -url=jdbc:postgresql://db:5432/eight_queens_db
      -user=${POSTGRES_USER}
      -password=${POSTGRES_PASSWORD}
      migrate
    volumes:
      - ./migrations:/flyway/sql

  app:
    build:
      context: .
    container_name: eight_queens_app
    restart: always
    depends_on:
      - db
    command:
      [
        "uvicorn",
        "src.app:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8080",
        "--reload",
      ]
    ports:
      - "8080:8080"
    volumes:
      - .:/app
volumes:
  db:
