version: "3"

services:
  app:
    build: .
    container_name: eight_queens
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://queens:queens12345/eight_queens
    depends_on:
      - db
    networks:
      - .:/app

  db:
    image: postgres:13
    container_name: eight_queens_db
    environment:
      POSTGRES_USER: queens
      POSTGRES_PASSWORD: queens12345
      POSTGRES_DB: eight_queens
    ports:
      - "5432-5432"
