name: Postgres Compose CI

on:
  pull_request:
    branches:
      - main

jobs:
  postgres:
    runs-on: ubuntu-latest

    steps:
    - name: Start PostgreSQL
      run: |
        sudo service postgresql start
        echo "Waiting for PostgreSQL to start..."
        sleep 10
      env:
        POSTGRES_USER: ${{ vars.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ vars.POSTGRES_DB }}

    - name: Set up database
      run: |
        psql -U ${{ vars.POSTGRES_USER }} -c "CREATE DATABASE ${{ vars.POSTGRES_DB }};" || echo "Database already exists"
        psql -U ${{ vars.POSTGRES_USER }} -d ${{ vars.POSTGRES_DB }} -c "GRANT ALL PRIVILEGES ON DATABASE ${{ vars.POSTGRES_DB }} TO ${{ vars.POSTGRES_USER }};" || echo "Privileges already granted"

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 5
        done

    - name: Run Flyway migrations
      uses: red-gate/FlywayGitHubAction@main
      with:
        url: jdbc:postgresql://localhost:5432/eight_queens_db
        user: ${{ vars.POSTGRES_USER }}
        password: ${{ secrets.POSTGRES_PASSWORD }}
        locations: filesystem:./migrations
        extraArgs: -outOfOrder=true
        

